version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: chroma
      POSTGRES_USER: chroma
      POSTGRES_PASSWORD: chroma
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rag-backend:
    build: ./rag-backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE=postgresql://chroma:chroma@db:5432/chroma
      - USE_LOCAL_EMBEDDINGS=${USE_LOCAL_EMBEDDINGS}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
